name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node }}'
          cache: 'pnpm'
      - name: Install packages
        run: pnpm i
      - name: Run test
        run: pnpm t
      - name: Run lint
        run: pnpm lint
